// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASRwMzIQGyydlOhqG1RVQTRtstNJthg-Y',
    appId: '1:275828398349:web:135b40b70b93807b8d3844',
    messagingSenderId: '275828398349',
    projectId: 'recipeapp-85fd0',
    authDomain: 'recipeapp-85fd0.firebaseapp.com',
    storageBucket: 'recipeapp-85fd0.firebasestorage.app',
    measurementId: 'G-RNQMXSY33C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhMPXlnN_oMf2b_nMtnKN2oSV1EkK36LA',
    appId: '1:275828398349:android:dd21fb1dd5cf484f8d3844',
    messagingSenderId: '275828398349',
    projectId: 'recipeapp-85fd0',
    storageBucket: 'recipeapp-85fd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACjBBO6pZFzQmvNc3vI06KmkvIxMtHFxM',
    appId: '1:275828398349:ios:f24b108ef7922d4f8d3844',
    messagingSenderId: '275828398349',
    projectId: 'recipeapp-85fd0',
    storageBucket: 'recipeapp-85fd0.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACjBBO6pZFzQmvNc3vI06KmkvIxMtHFxM',
    appId: '1:275828398349:ios:f24b108ef7922d4f8d3844',
    messagingSenderId: '275828398349',
    projectId: 'recipeapp-85fd0',
    storageBucket: 'recipeapp-85fd0.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASRwMzIQGyydlOhqG1RVQTRtstNJthg-Y',
    appId: '1:275828398349:web:28d2812e20abed338d3844',
    messagingSenderId: '275828398349',
    projectId: 'recipeapp-85fd0',
    authDomain: 'recipeapp-85fd0.firebaseapp.com',
    storageBucket: 'recipeapp-85fd0.firebasestorage.app',
    measurementId: 'G-MFNJQ1EWHW',
  );
}
